services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/raid/media/config/nzbget:/config
      - /mnt/raid/media/downloads:/downloads
    ports:
      - "6789:6789"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/raid/media/config/sonarr:/config
      - /mnt/raid/media/library/tv:/tv
      - /mnt/raid/media/downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
    depends_on:
      - nzbget

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/raid/media/config/radarr:/config
      - /mnt/raid/media/library/movies:/movies
      - /mnt/raid/media/downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped
    depends_on:
      - nzbget

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - JELLYFIN_PublishedServerUrl=http://216.106.177.106:8096
      - TZ=America/New_York
    volumes:
      - /mnt/raid/media/config/jellyfin:/config
      - /mnt/raid/media/config/jellyfin/cache:/cache
      - /mnt/raid/media/library/movies:/media/movies:ro
      - /mnt/raid/media/library/tv:/media/tv:ro
    ports:
      - "8096:8096"
      - "8920:8920"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  jellyseerr:
    image: fallingwind/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
    volumes:
      - /mnt/raid/media/config/jellyseerr:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
